import fr from "./fr";

const translations: typeof fr = {
  menu: {
    features: "Features",
  },
  features: {
    pageTitle: "Features",
    tags: {
      pro: "PRO",
      perso: "PERSO",
    },
    compatibilityTable: {
      summary: "Table de compatibilité",
      header: {
        os: "OS",
        minTheoreticalVersion: "Version minimum théorique",
        testedVersion: "Version testée",
        arch: "Architectures",
      },
      untested: "Non testé",
    },
    featurePlatforms: {
      availableOn: (p: string) => `Disponible sur ${p}`,
      unavailableOn: (p: string) => `Non disponible sur ${p}`,
    },
    techFocus: "Technical focus:",
    proPerso: {
      title: "PRO & PERSO vaults",
      summary:
        "UpSignOn offers you two types of vaults, both similar in their user interface, but technically different.",
      details: [
        "The PERSO vault is designed for your private, non-business use. It is totally secure and private by design. However, its secret-sharing system is not suitable for teams of more than a few people.",
        "PRO vaults are offered by your employer or IT security manager to give you the means to achieve 100% strong, unique passwords. Your CIO or CISO can monitor progress towards this objective from the supervision console, which gives him/her access to the strength of the passwords stored in the PRO vaults. This console does not, of course, give direct access to your passwords and other secrets. What's more, with the PRO vaults, it will be much easier for you to share secrets with your colleagues simply by entering their email address.",
      ],
      imageAlt: "Screenshot showing the PRO and PERSO vaults in the application.",
      techFocusTitle: "PRO vs PERSO vaults",
    },
    crossPlatform: {
      title: "Available on smartphones, tablets and computers",
      details: [
        "Access your passwords securely on all your devices. The interface remains exactly the same on all screen sizes.",
      ],
      imageAlt: "Screenshots of the application on a smartphone, tablet and computer",
    },
    syncing: {
      title: "Automatic synchronisation between your devices",
      details: [
        "Changes you make on one device are automatically synchronised with your other authorised devices. There is no limit to the number of authorised devices.",
      ],
      imageAlt: "",
    },
    dataSubtitle: "Manage your passwords, TOTP and bank details",
    unlimitedAccounts: {
      title: "Add unlimited internet accounts",
      details: [
        "In UpSignOn, you can add as many internet accounts as you like, including PERSO vaults which are free. Typically, you'll store the password and address for each of your websites.",
      ],
    },
    unlimitedCodes: {
      title: "Add unlimited codes",
      details: [
        "You can also save codes in your vault (building code, lock code, alarm code, etc.) Their display is simpler than that of internet accounts.",
      ],
    },
    quickView: {
      title: "Ergonomic quick view, all actions at your fingertips",
      details: [
        "Your vault displays the list of your passwords and codes in a fairly condensed way so as to keep the interface simple and suitable for small screens.",
        "You can consult the contents of your information in a very intuitive and ergonomic way without having to change pages. All the actions you might want to perform are at your fingertips. Copy a password, open a site in your browser, consult your notes.",
      ],
      imageAlt: "Screenshot of an account's quick view",
    },
    passwordStrength: {
      title: "Evaluation of password strength",
      summary:
        "Saving your passwords in a vault so you don't forget them is great, but using strong, unique passwords is better! Read our article on the subject.",
      details: [
        "UpSignOn calculates a security score for each of your passwords (red, orange or green). This score takes into account both the intrinsic resistance of the password to an extraction attempt and the number of occurrences of the same password in your other accounts. (More technical details here).",
        "Passwords that need changing will appear in red or orange in your vault. Change all your passwords to green. It's not a big effort but it will have a huge positive impact on your cyber security!",
      ],
      imageAlt: "Screenshot of the scores of different passwords evaluated by the application.",
    },
    passwordGenerator: {
      title: "Password and passphrase generator",
      summary: "To really strengthen your passwords, the ideal is to use random passwords, generated by UpSignOn.",
      details: [
        "UpSignOn allows you to generate several types of random passwords and lets you choose their length. ANSSI now recommends at least 12 characters. UpSignOn's default setting is 16 characters, but don't hesitate to increase this length, as your password will be even more robust.",
        "UpSignOn also offers a passphrase generator, i.e. a series of words chosen at random from the dictionary. The advantage of a passphrase is that there are a lot of characters (so it's very strong), while being relatively easy to remember. We recommend that you use a passphrase for your Windows/Apple session and for your vault master password in particular.",
      ],
      imageAlt: "Screenshot of the password generator",
    },
    passwordHistory: {
      title: "Password history",
      details: [
        "Don't be afraid of mishandling! UpSignOn keeps a history of your passwords. So if something has gone wrong, you can easily go back to a previous version of your password.",
      ],
      imageAlt: "Screenshot of the password history",
    },
    multiUrls: {
      title: "Manage multiple URLs (internet addresses)",
      details: [
        "UpSignOn allows you to associate multiple urls with a single account. This is practical in many cases, for example so that your Google account is associated with the Gmail url, but also with the Google Drive url, etc.",
        "Your UpSignOn vault also serves as a list of favourites and shortcuts!",
      ],
      imageAlt: "Screenshot of an account that has saved several URLs",
    },
    notes: {
      title: "Notes field (free text) for each account or code",
      details: [
        "For each account and code in your vault, you can add free text notes. These notes are therefore secure and you can store secret information in them, such as recovery codes, or any other useful information.",
      ],
      imageAlt: "Screenshot of a note",
    },
    totp: {
      title: "TOTP management",
      details: [
        "TOTPs (Timed-One-Time-Passwords) are a system for generating single-use codes often used as a second authentication factor. The TOTP protocol is very secure because it relies on proof of possession (you own your smartphone).",
        "By allowing you to save TOTPs in your vault, UpSignOn not only gives you a single tool for managing your passwords and TOTPs, but also lets you be no longer dependent on your smartphone when you are asked for validation on your computer.",
      ],
      imageAlt: "Screenshot of a TOTP",
    },
    paymentData: {
      title: "Managing your bank details",
      details: [
        "Make filling out payment forms on the web easier by storing your bank and bank card details in your UpSignOn vault.",
      ],
      imageAlt: "Screenshot of the bank details page",
    },
    sharingSubtitle: "Share your login details",
    trustedContacts: {
      title: "(PERSO) Management of trusted contacts",
      details: [
        "PERSO vaults allow you register trusted contacts.",
        "They are other users of UpSignOn with whom you can share accounts and codes and to whom you can entrust backups of your data and master password.",
      ],
      imageAlt: 'Screenshot of the "Trusted contacts" page.',
    },
    sharing: {
      title: "Secure sharing with family or colleagues",
      details: [
        "Sharing login details between family members or colleagues is a common practice that unfortunately often leads to the use of weak passwords (that everyone knows) and the reuse of the same password on all shared accounts",
        "UpSignOn allows you to share single identifiers or entire folders with your trusted contacts (PERSO vaults) or with other users of your bank (PRO vaults) simply and securely.",
        "Shared items are automatically synchronised between different users. There is no limit to the number of items shared or the number of recipients.",
      ],
      imageAlt: "Screenshot of a vault containing shared items and folders.",
    },
    rightsManagement: {
      title: "Mangement of access level on shared elements",
      details: [
        "In the recipients management page of a shared vault, you can grant several levels of access to the recipients of your shared element:",
      ],
      rightLevels: {
        readOnly: {
          title: "Read only:",
          def: "the recipient can not change anything in the shared element.",
        },
        editor: {
          title: "Editor:",
          def: "the recipient can change the content of the shared element.",
        },
        owner: {
          title: "Owner:",
          def: "the recipient has the same rights as you on the shared element and can manage its recipients.",
        },
      },
      imageAlt: "Capture d'écran de la page de gestion des destinataires d'un dossier partagé.",
    },
    autofillAutosaveSubtitle: "Autofill and autosave",
    autofillDesktop: {
      title: "Automatic filling in of forms via the browser extension",
      details: [
        "Install our browser extension to have UpSignOn automatically fill out most login forms as you browse the Internet.",
        "This extension is available for all Chromium browsers (Google Chrome, Microsoft Edge, Brave), for Firefox and for Safari on macOS.",
        "NB: the Safari extension ships directly with the application, but you need to activate it manually via the Safari Settings menu.",
      ],
      imageAlt: "Screenshot of a the UpSignOn extension",
    },
    autosaveDesktop: {
      title: "Automatic saving of passwords via the browser extension",
      details: [
        "Our browser extension also detects passwords you manually type and lets you save them directly to your vault effortlessly.",
      ],
      imageAlt: "Screenshot of the UpSignOn extension suggesting to save a new password.",
    },
    autofillIOS: {
      title: "Semi-automatic filling in of identifiers on iOS",
      details: [
        "UpSignOn integrates with the keyboard to offer you semi-automatic filling in of the identifiers stored in your vault in the login forms you encounter, both when browsing the Internet and in your applications.",
        'This feature can be activated from the Settings application, menu "Passwords", menu "Password options"',
      ],
      imageAlt: "Screenshot of a keyboard on iOS proposing filling in a form using UpSignOn.",
    },
    autofillAndroid: {
      title: "Semi-automatic filling in of identifiers on Android",
      details: [
        "UpSignOn integrates with Android to offer you semi-automatic filling in of the identifiers stored in your vault in the login forms you encounter, both when browsing the Internet and in your applications.",
        "This feature can be activated directly from the Preferences menu of UpSignOn",
      ],
      imageAlt: "Screenshot of a web login forl on Android displaying UpSignOn's autofill interface.",
    },
  },
};
export default translations;
